# app/config/security.yml
imports : 
  - {resource :"@UserBundle/Resources/config/security.yml"}
jms_security_extra:
  secure_all_services: false
  expressions: true

security:
   
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /candidat/*, role: ROLE_USER }
        - { path: /filiere/*, role: ROLE_ADMIN }
       
     