<?php

namespace mqlUIT\CandidatureBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FiltreController__JMSInjector
{
    public static function inject($container) {
        $instance = new \mqlUIT\CandidatureBundle\Controller\FiltreController();
        return $instance;
    }
}
