<?php

namespace mqlUIT\CandidatureBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ExperiencetypeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \mqlUIT\CandidatureBundle\Controller\ExperiencetypeController();
        return $instance;
    }
}
