<?php

namespace mqlUIT\CandidatureBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DiplometypeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \mqlUIT\CandidatureBundle\Controller\DiplometypeController();
        return $instance;
    }
}
