security:
        encoders:
            FOS\UserBundle\Model\UserInterface: sha512

        providers:
                fos_userbundle:
                    id: fos_user.user_provider.username

        firewalls:
                dev :
                    pattern: ^/(_(profiler|wdt))/
                    security: false
                main:
                    pattern: ^/
                    access_denied_url: /login
                    form_login:
                        provider:           fos_userbundle
                        csrf_provider:      form.csrf_provider
                        login_path:         /login
                        use_forward :       false
                        check_path:         /login_check
                        failure_path:       null
                        default_target_path: /redirection
                        remember_me:        true
                          
                    remember_me:
                      key:      %secret%
                      lifetime: 30000000
                      path:     /
                      domain:  ~
                    logout:       
                      target : /login
                    anonymous:    true