mqlUIT\CandidatureBundle\Entity\Candidature:
    type: entity
    table: candidature
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        isvalid:
            type: string
            length: 1
            fixed: false
            nullable: true
    manyToOne:
        candidat:
            targetEntity: Candidat
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                candidat_id:
                    referencedColumnName: id
            orphanRemoval: false
        filiere:
            targetEntity: Filiere
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Filiere_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
