mqlUIT\CandidatureBundle\Entity\Candidat:
  
    type: entity
    table: candidat
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nom:
            type: string
            length: 45
            fixed: false
            nullable: false
        prenom:
            type: string
            length: 45
            fixed: false
            nullable: false
        datenaissance:
            type: date
            nullable: false
        adresse:
            type: string
            length: 200
            fixed: false
            nullable: false
        cin:
            type: string
            length: 45
            fixed: false
            nullable: false
        cne:
            type: string
            length: 45
            fixed: false
            nullable: false
        email:
            type: string
            length: 150
            fixed: false
            nullable: false
        telephone:
            type: string
            length: 45
            fixed: false
            nullable: false
        nationalite:
            type: string
            length: 45
            fixed: false
            nullable: false
        ville:
            type: string
            length: 45
            fixed: false
            nullable: false
        pays:
            type: string
            length: 45
            fixed: false
            nullable: false
        sexe:
            type: string
            length: 10
            fixed: false
            nullable: false
    manyToOne:
        userfos:
            targetEntity: \mqlUIT\UserBundle\Entity\UserFOS
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userfos_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
