mqlUIT\CandidatureBundle\Entity\DetailSemestre:
    type: entity
    table: detail_semestre
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        note:
            type: decimal
            precision:  10
            scale: 10
            nullable: true
        hasrattrapage:
            type: string
            length: 3
            fixed: false
            nullable: true
    manyToOne:
        semestre:
            targetEntity: Semestre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                semestre_id:
                    referencedColumnName: id
            orphanRemoval: false
        candidat:
            targetEntity: Candidat
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                candidat_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
