mqlUIT\CandidatureBundle\Entity\FiltreFiliere:
    type: entity
    table: filtre_filiere
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        coefficcient:
            type: integer
            unsigned: false
            nullable: true
    manyToOne:
        filiere:
            targetEntity: Filiere
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Filiere_id:
                    referencedColumnName: id
            orphanRemoval: false
        filtre:
            targetEntity: Filtre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Filtre_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
