mqlUIT\CandidatureBundle\Entity\Responsable:
    type: entity
    table: responsable
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nom:
            type: string
            length: 45
            fixed: false
            nullable: true
        prenom:
            type: string
            length: 45
            fixed: false
            nullable: true
        email:
            type: string
            length: 150
            fixed: false
            nullable: true
    manyToOne:
        userfos:
            targetEntity: \mqlUIT\UserBundle\Entity\UserFOS
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userfos_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
