mqlUIT\CandidatureBundle\Entity\Semestre:
    type: entity
    table: semestre
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        semestre:
            type: string
            length: 45
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
